#!/usr/bin/env bash

outfile=$2

# ignore the line number for the actual halt call (since it's internal and the
# line number will change frequently)
sed "s:\(halt() at \$CHPL_HOME/modules/.*.chpl\:\)[0-9]*:\1nnnn:g" $outfile > $outfile.tmp
mv $outfile.tmp $outfile

# Replace number of omitted frames since that can change.
sed 's/[0-9]\+ omitted/n omitted/g' $outfile > $outfile.tmp
mv $outfile.tmp $outfile
